// Code generated by "stringer -type SigTag"; DO NOT EDIT.

package rpm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RPMTAG_SIG_BASE-256]
	_ = x[RPMSIGTAG_SIZE-1000]
	_ = x[RPMSIGTAG_LEMD5_1-1001]
	_ = x[RPMSIGTAG_PGP-1002]
	_ = x[RPMSIGTAG_LEMD5_2-1003]
	_ = x[RPMSIGTAG_MD5-1004]
	_ = x[RPMSIGTAG_GPG-1005]
	_ = x[RPMSIGTAG_PGP5-1006]
	_ = x[RPMSIGTAG_PAYLOADSIZE-1007]
	_ = x[RPMSIGTAG_RESERVEDSPACE-1008]
	_ = x[RPMSIGTAG_BADSHA1_1-1009]
	_ = x[RPMSIGTAG_BADSHA1_2-1010]
	_ = x[RPMSIGTAG_DSA-1011]
	_ = x[RPMSIGTAG_RSA-1012]
	_ = x[RPMSIGTAG_SHA1-1013]
	_ = x[RPMSIGTAG_LONGSIZE-1014]
	_ = x[RPMSIGTAG_LONGARCHIVESIZE-1015]
	_ = x[RPMSIGTAG_SHA256-1016]
	_ = x[RPMSIGTAG_FILESIGNATURES-291]
	_ = x[RPMSIGTAG_FILESIGNATURESLENGTH-292]
}

const (
	_SigTag_name_0 = "RPMTAG_SIG_BASE"
	_SigTag_name_1 = "RPMSIGTAG_FILESIGNATURESRPMSIGTAG_FILESIGNATURESLENGTH"
	_SigTag_name_2 = "RPMSIGTAG_SIZERPMSIGTAG_LEMD5_1RPMSIGTAG_PGPRPMSIGTAG_LEMD5_2RPMSIGTAG_MD5RPMSIGTAG_GPGRPMSIGTAG_PGP5RPMSIGTAG_PAYLOADSIZERPMSIGTAG_RESERVEDSPACERPMSIGTAG_BADSHA1_1RPMSIGTAG_BADSHA1_2RPMSIGTAG_DSARPMSIGTAG_RSARPMSIGTAG_SHA1RPMSIGTAG_LONGSIZERPMSIGTAG_LONGARCHIVESIZERPMSIGTAG_SHA256"
)

var (
	_SigTag_index_1 = [...]uint8{0, 24, 54}
	_SigTag_index_2 = [...]uint16{0, 14, 31, 44, 61, 74, 87, 101, 122, 145, 164, 183, 196, 209, 223, 241, 266, 282}
)

func (i SigTag) String() string {
	switch {
	case i == 256:
		return _SigTag_name_0
	case 291 <= i && i <= 292:
		i -= 291
		return _SigTag_name_1[_SigTag_index_1[i]:_SigTag_index_1[i+1]]
	case 1000 <= i && i <= 1016:
		i -= 1000
		return _SigTag_name_2[_SigTag_index_2[i]:_SigTag_index_2[i+1]]
	default:
		return "SigTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
