// Code generated by "stringer -type TagType"; DO NOT EDIT.

package rpm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[Char-1]
	_ = x[Int8-2]
	_ = x[Int16-3]
	_ = x[Int32-4]
	_ = x[Int64-5]
	_ = x[String-6]
	_ = x[Bin-7]
	_ = x[StringArray-8]
	_ = x[I18nString-9]
}

const _TagType_name = "NullCharInt8Int16Int32Int64StringBinStringArrayI18nString"

var _TagType_index = [...]uint8{0, 4, 8, 12, 17, 22, 27, 33, 36, 47, 57}

func (i TagType) String() string {
	if i < 0 || i >= TagType(len(_TagType_index)-1) {
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagType_name[_TagType_index[i]:_TagType_index[i+1]]
}
